version: '3.7'
services:
  database:
    image: 'mariadb:10.1.48'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  app:
    depends_on:
      - database
    volumes:
      - ./site:/var/www/html
    ports:
      - 8000:80
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      BAJO_DATABASE_URL: "mysql://root:${MYSQL_ROOT_PASSWORD}@database:3306/${MYSQL_DATABASE}?charset=utf8mb4"
      BAJO_APP_ENV: ${APP_ENV}
      BAJO_APP_SECRET: ${APP_SECRET}